name: Quark签到

on:
  schedule:
    - cron: '0 1 * * *'    # 每天 09:00 (北京时间)
    - cron: '0 5 * * *'    # 每天 13:00 (北京时间)
  workflow_dispatch:       # 手动触发支持

jobs:
  check-if-already-signed:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 下载签到记录
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: last-success-date
          path: .

      - name: 判断是否已签到
        id: check
        run: |
          current_date=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
          echo "当前北京时间: $current_date"

          if [ -f .last_success_date ]; then
            last_date=$(cat .last_success_date)
            echo "上次签到日期: $last_date"
            if [ "$last_date" = "$current_date" ]; then
              echo "今天已成功签到，跳过执行。"
              echo "skip=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi

          echo "今天尚未签到，继续执行。"
          echo "skip=false" >> "$GITHUB_OUTPUT"

  sign-in:
    needs: check-if-already-signed
    if: needs.check-if-already-signed.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 执行签到脚本
        env:
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python checkIn_Quark.py

      - name: 标记今天签到成功
        run: |
          date_str=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
          echo "$date_str" > .last_success_date
          ls -l .last_success_date

      - name: 上传签到日期到 artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-success-date
          path: .last_success_date
