name: Quark签到

on:
  schedule:
    - cron: '0 1 * * *'    # 每天 UTC 1:00（北京时间 9:00）
    - cron: '0 5 * * *'    # 每天 UTC 5:00（北京时间 13:00）
  workflow_dispatch:       # 支持手动触发

jobs:
  check-if-already-signed:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 下载签到记录
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: last-success-date
          path: ./

      - name: 移动签到记录文件
        run: |
          # 处理下载的Artifact（如果存在）
          if [ -d last-success-date ]; then
            mv last-success-date/.last_success_date ./ 2>/dev/null || true
          fi

      - name: 初始化签到记录
        run: |
          if [ ! -f .last_success_date ]; then
            echo "初始化签到记录文件..."
            echo "1970-01-01" > .last_success_date
          fi
          echo "当前记录内容: $(cat .last_success_date)"

      - name: 判断签到状态
        id: check
        run: |
          current_date=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
          last_date=$(cat .last_success_date)
          
          echo "当前日期: $current_date"
          echo "最后签到: $last_date"
          
          if [ "$last_date" = "$current_date" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "::notice::今天已签到，跳过"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "::notice::需要签到"
          fi

  sign-in:
    needs: check-if-already-signed
    if: needs.check-if-already-signed.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 随机延迟
        run: |
          delay=$(( RANDOM % 60 ))
          echo "随机延迟 $delay 秒..."
          sleep $delay

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install requests

      - name: 执行签到脚本
        env:
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python checkIn_Quark.py
          if [ $? -eq 0 ]; then
            date_str=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
            echo "$date_str" > .last_success_date
            echo "✅ 签到成功，日期更新为: $date_str"
          else
            echo "❌ 签到失败，保留旧日期"
            exit 1
          fi

      - name: 上传签到记录
        uses: actions/upload-artifact@v4
        with:
          name: last-success-date
          path: .last_success_date
          retention-days: 30

      - name: 调试输出
        run: |
          echo "=== 调试信息 ==="
          ls -la
          echo "文件内容: $(cat .last_success_date)"
